all:
  recaptcha:
    extended_form_class:    sfReCaptchaForm
    
    recaptcha_public_key:   6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX
    recaptcha_private_key:  6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb
    
    # A collection of form classes that will automatically be setup with recaptcha
    forms:                  []
      #myFormClass:    true